<?php

namespace AppBundle\Entity;

/**
 * AdressesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdressesRepository extends \Doctrine\ORM\EntityRepository
{
}
