<?php

namespace AppBundle\Entity;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{


   public function insertFromCSV($data){

   	  $pdo = $this->getEntityManager()->getConnection()->getWrappedConnection();
        $pdo->setAttribute(\PDO::MYSQL_ATTR_USE_BUFFERED_QUERY, false);
        $sql = sprintf("UPDATE MIGRATION M
                        LEFT JOIN SFR_GRO_MAIL SGM ON M.ID_SFR_GRO_MAIL = SGM.ID_SFR_GRO_MAIL
                        SET M.STATUT = 'INFORMER_SFR_OK', SGM.STATUT = 'CONFIRME', SGM.DATE_RETOUR_SFR = NOW()
                        WHERE (SGM.TOKEN = '%s' AND M.STATUT = 'INFORMER_SFR_NOTIFIER')", $token);

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        return $stmt->execute();
   }

	
}
