<?php

namespace AppBundle\Entity;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllClients($offset, $limit){
         return $this->createQueryBuilder('d')
              ->select('d.nom, d.prenom, d., d.email, d.naissance, d.sexe')
              ->getQuery()
              ->setFirstResult( $offset )
              ->setMaxResults( $limit )
              ->getResult();
    }
}
