<?php

namespace AppBundle\Entity;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllClients($offset, $limit){
         return $this->createQueryBuilder('d')
              ->select('d')
              ->getQuery()
              ->setFirstResult( $offset )
              ->setMaxResults( $limit )
              ->getResult();
    }
    
    public function getCount(){
        return $this->createQueryBuilder('d')
              ->select('count(d.id)')
              ->getQuery()
              ->getSingleResult();
                  
    }
}
